name:                yaml-parser
version:             0.1.0.0
github:              "nmjr-311/yaml-parser"
license:             BSD3
author:              "nmjr-311"
maintainer:          "nmjr31@gmail.com"
copyright:           "nmjr-311"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nmjr-311/yaml-parser#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.14
- text >= 1.2
- hspec
- QuickCheck

library:
  source-dirs: src

default-extensions:
  - GADTs
  - OverloadedStrings
  - LambdaCase
  - DeriveGeneric
  - GeneralizedNewtypeDeriving

executables:
  yaml-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yaml-parser

tests:
  yaml-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yaml-parser
    - hspec
    - QuickCheck
